[package]
name = "wisp-text"
description = "Shaping, rasterising and caching glyphs for wisp."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
wisp-core.workspace = true
cosmic-text = "0.19"
etagere = "0.3"
